server:
  port: 8081
spring:
  application:
    name: user-subscriptions
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_subscriptions}
    username: user_subscriptions
    password: user_subscriptions
  flyway:
    schemas:
      - user_subscriptions
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_subscriptions
  sql:
    init:
      mode: always