CREATE SCHEMA IF NOT EXISTS user_subscriptions;


-- Устанавливаем рабочую схему
SET search_path TO user_subscriptions;

CREATE TABLE user_subscriptions.users (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version BIGINT
);

CREATE TABLE user_subscriptions.subscriptions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   user_id BIGINT NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version BIGINT,
   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_users_username ON user_subscriptions.users (username);
CREATE UNIQUE INDEX idx_user_subscriptions_name_user ON user_subscriptions.subscriptions (name, user_id);